<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="tag" uri="http://www.jksoft.com/taglib/tag" %>
<%@ taglib prefix="function" uri="http://www.jksoft.com/taglib/function" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%-- 
    JSP Name : inc_footer.jsp
    Description : 페이지 하단을 장식한다.
--%>
<div id="ctt_con" class="">
	<div class="et_pb_text_inner"><h3><strong>Privacy Policy</strong></h3>
	<p>Last Updated: January 31, 2022</p>
	<p>The goal of Voice Caddie is to help users live healthier and more active lifestyles.</p>
	<p>Voice Caddie’s products and services provide instant access and useful feedback to golf and fitness activity data so users can monitor their golf scores and progress, push their golf record goals, and take control of their personal activity record.</p>
	<p>Voice Caddie’s employees are committed to the principles of respecting user’s privacy, keeping user’s data safe, managing user’s data efficiently and letting user decide how their information is used and shared as we build these outputs.</p>
	<p>Voice Caddie’s Privacy Pledge is as follows…</p>
	<ul>
	<li>Voice Caddie will only collect data that is useful to improving Voice Caddie products, services, and user experience.</li>
	<li>Voice Caddie will be transparent about how we handle and use user data.</li>
	<li>Voice Caddie will never sell our user’s data and will only share personally identifiable data when users allow us to (or under the circumstances outlined in our Privacy Policy).</li>
	<li>Voice Caddie will always take the security of user data seriously.</li>
	</ul>
	<p>To learn more about the data we collect, how that data is used, and the ways it can be shared both by us and users, please read our Privacy Policy Statements below.</p>
	<p><strong>Voice Caddie Privacy Policy</strong></p>
	<p>Voice Caddie designs products and services that monitor usual golf and fitness activity to empower and inspire users powerfully to lead healthier, more valuable active lives based on improved data. This Privacy Policy applies to our personal golf &amp; fitness activity, record monitoring products (“Devices”), our websites located at www.voicecaddie.com, the Voice Caddie Manager (VCM: “Software and Firmware”) and Voice Caddie mobile applications (APP). The Devices, Sites, Software and Apps are collectively referred to in this Policy as the “Voice Caddie-service,” and by proceeding to use the Voice Caddie-service, users consent that we may process the data that we collect from user in accordance with this Privacy Policy. Because we’re always looking for easy &amp; new and innovative ways to help our users achieve their improving golf and fitness activity goals, this policy may change over time, but we clarify that any future changes will never affect data that was collected under a previous version of this policy.</p>
	<p>If any modifications substantially change user’s rights, we will instantly send an email with summary of the changes to the address associated with Voice Caddie account and notify on the site clearly.</p>
	<p>Voice Caddie collects data as follows:</p>
	<p><strong>When user creates a Voice Caddie account:</strong></p>
	<p>To access data including golf and fitness records collected by user’s own Device, users must create a Voice Caddie account. At that time, users need to be asked some personal information, including user’s email address and date of birth or demography. Email address that users already have will be user’s Voice Caddie account username, which users will use to log-into their account. We don’t expose user email address to other users. Others will see on behalf of the name or nickname users enter in user’s profile settings. Users can also create user’s Voice Caddie account using a different way such as a Facebook or Kakao talk account. At that time, users need to be asked permission to access basic information from that account, such as username, picture for profile, and friend list. Users can also stop sharing that information with us at any time by removing Voice Caddie’s access to that account. We will access user’s phone’s contact list for the purpose of letting user identify contacts who are Voice Caddie users. Even in this time, we never store user’s phone’s contact list, and it is deleted immediately after it is performed for this purpose.</p>
	<p><strong>When users add information to an account:</strong></p>
	<p>Users can customize their Voice Caddie experience by adding other types of information to their account, such as entering a golf log, setting an alarm, decorating user’s profile with pictures, participating in community, sending messages to user’s Voice Caddie friends. Whenever users add this type of data on communication boards or community list, Voice Caddie collects them, stores them in user’s Voice Caddie account</p>
	<p><strong>When user visit Voice Caddie web/app sites:</strong></p>
	<p>Voice Caddie collects ISD (industry standard data) from everyone who visits Voice Caddie’s web/app sites, even if users don’t have a Voice Caddie account. This includes web log data that automatically records information about user’s visit, such as user’s browser type, OS (operating system), the URL of the page that referred link, the different actions user performed, and the IP address user used to access the site. We use this type of information to provide user with an experience that’s relevant to user’s location based on the IP address, to prevent site misuse &amp; abuse, and to ensure the site is working properly. We also collect data from internet cookies. To see the full list cookies, we use and how we use them, please read our Cookie Policy.</p>
	<p><strong>When user sync their own Voice Caddie device:</strong></p>
	<p>When user sync their own Voice Caddie device through an App or the software &amp; firmware, data recorded on user’s Device about their activity is transferred from their Device to our servers. This data is stored and used to provide the Voice Caddie Service and is associated with user’s account. Each time sync occurs, we record the log data about the transmission. It includes the log data are the sync time and date, device battery level, and the IP address used when syncing.</p>
	<p><strong>When user purchases from Voice Caddie online store:</strong></p>
	<p>Voice Caddie never view or store user’s credit card information. This is handled by our third-party payment processor. Voice Caddie store user’s shipping address so we can process our user’s order through our fulfillment partner. If users are logged into their Voice Caddie account when users purchase something on Voice Caddie online store, we associate that order contents with user’s Voice Caddie account.</p>
	<p><strong>When user contact us for inquiries or help:</strong></p>
	<p>Whenever users contact Voice Caddie for inquiries or help, we collect username and email address along with additional information user provide in their request so that we can provide them with assistance and improve the Voice Caddie service. If users contact us when they are already logged in to user account, the web-based form automatically pre-fills this information, so users don’t have to type it manually inconveniently. Users can also contact Voice Caddie on public forums such as Twitter or Facebook; however, we cannot guarantee or maintain the privacy of user’s communication to us if users contact us through these routes.</p>
	<p><strong>When user add friends:</strong></p>
	<p>To help users stay motivated on their golf and fitness activity like a cycle and running, Voice Caddie provides user to add friends who are already Voice Caddie users or invite friends who have not yet joined. Users can add friends in several ways, such as by providing their email addresses, or by accessing social networking accounts or from the contact list on their smartphone. When users share their friends’ contact information with us to add them as a friend, we will only use it for this purpose. We never store user phone’s contact list, and it is deleted immediately after it is performed for this purpose.</p>
	<p><strong>When user activate LBF (location-based features):</strong></p>
	<p>The Voice Caddie service includes features that require the collection of specific location data, including GPS signals, device several sensors, Wi-Fi access points etc. We only collect this type of data when users activate a location feature, such as golf distance recording. We stop collecting this type of data instantly when users deactivate the feature. We store this information in user’s Voice Caddie account. If users are using a marking on a map feature, we will send their location information to our marks on a map service provider so they can display user’s location on a map.</p>
	<p><strong>Information from other uncertain sources:</strong></p>
	<p>We never collect any information about users from other sources outside of their interaction with the Voice Caddie service.</p>
	<p><strong>How We Use User Data:</strong></p>
	<p>Voice Caddie uses user’s data to provide them with the best experience possible, to help user make the most of their golf and fitness activity tracking, and to improve and protect the Voice Caddie service.</p>
	<p>Making good use of data is as follows:</p>
	<ul>
	<li>Height, weight, gender, and age are used to estimate/calculate the calorie requirements as accurate as possible when users exercise using by device.</li>
	<li>Contact information is used to send users notifications, allow other Voice Caddie users to add user as a friend, and to inform our users about new features or products that users would be interested in. Please read “Refuse to receive the Voice Caddie Emails” for information on how users can refuse to receive all communications.</li>
	<li>Data and logs are used in research to understand and improve the Voice Caddie device and service; to troubleshoot the Voice Caddie service; to detect and protect against error, fraud, or other criminal activity; and to enforce the Voice Caddie terms of service.</li>
	<li>Anonymous data that does not identify individuals may be used to inform the golf tips community about trends; for marketing and promotional use; or for sale to interested audiences. See “Sharing of personally unidentifiable information” to learn more.</li>
	</ul>
	<p><strong>What data may be shared with 3rd Parties:</strong></p>
	<p>Users keep our promise and trust. We don’t sell any data that could identify users: PII. We only share data about users when it is necessary to provide the individuals service, when the data is unidentified and aggregated, or when users allow us to share it.</p>
	<p><strong>Personally Identifiable Information:</strong></p>
	<p>Personally Identifiable Information (PII) is data that includes a personal identifier like username, email or address, or data that could reasonably be linked back to users. Voice Caddie will only share this data under only the following circumstances:<br>
	With companies that are contractually engaged in providing service us, such as order fulfillment, email management and credit card processing. These companies are obligated by contract to safeguard any PII they receive from us.<br>
	If we believe that disclosure is reasonably necessary to comply with a law, regulation, valid legal process (e.g., subpoenas or warrants served on us), or governmental or regulatory request, to enforce or apply the Terms of Service or Terms of Sale, to protect the security or integrity of the Voice Caddie Service, and/or to protect the rights, property, or safety of Voice Caddie, its employees, users, or others. If we are going to release user data, we will do our best to provide our users with notice in advance by email, unless we are prohibited by law from doing so.<br>
	We may disclose or transfer user’s PII in connection with the sale, merger, and bankruptcy, sale of assets or reorganization of our company. We will notify our users if a different company receives user’s PII and the promises in this Privacy Policy will apply to user data as transferred to the new entity.</p>
	<p><strong>Personally unidentifiable information (anonymous data):</strong></p>
	<p>Voice Caddie may share or sell aggregated, personally unidentifiable information that does not identify user, with partners and the public in a variety of ways, such as by providing research or report about golf and fitness activity or as part of our Platinum membership. When we provide this information, we perform appropriate and safe procedures so that the data never identify user, and we contractually prohibit recipients of the data from re-identifying it back to user.</p>
	<p><strong>Data that users allow us to share:</strong></p>
	<p>Users can direct and agree us to share data with 3rd parties. For example, user might authorize us to link user’s Voice Caddie account with a 3rd party app, send status updates to user’s Facebook, Twitter, or Kakao talk-story account, or direct and agree us to share data with user’s employer as part of a wellness program. Once user direct and agree us to share user’s data with a third party, that data is governed by the third-party’s privacy policy. User can revoke user’s consent to share with the third party at any time in user’s Voice Caddie account settings.</p>
	<p><strong>Other ways user might share user’s own data</strong></p>
	<p><strong>Default Visibility Settings:</strong></p>
	<p>The privacy settings on new Voice Caddie accounts are set to reveal minimal data about user with the purpose of getting user active and involved with the Voice Caddie service. To see what is visible to others use the “Scope of the public profile” tool in user’s account settings. Users can adjust user’s privacy settings under their account settings.</p>
	<p><strong>Community Posts:</strong></p>
	<p>To post to Voice Caddie community message boards list, users will be asked to create a community username that’s separate from user’s Voice Caddie profile name. This community username will be posted next to any comments user publish on community message boards. Other information, like a profile photo that users have added to user’s Voice Caddie account will also be visible on message boards, depending on user’s Voice Caddie account settings.</p>
	<p><strong>Contests and Giveaways:</strong></p>
	<p>Voice Caddie may offer opportunities to participate in contests, giveaways, and other promotions. Any data user submit in connection with these activities will be treated in accordance with this Privacy Policy unless the rules for those offers note otherwise.</p>
	<p><strong>Surveys:</strong></p>
	<p>Voice Caddie may also ask user to participate in surveys (processed by Voice Caddie or third parties) that help us understand user’s use of the Voice Caddie Service. Any PII users provide to Voice Caddie (or supplied by user or Voice Caddie to such third-party survey providers) in connection with these surveys will only be used in relation to that survey and as stated in this policy.</p>
	<p><strong>How Long We Save User Data:</strong></p>
	<p>Voice Caddie store user’s PII for as long as users maintain a Voice Caddie account.</p>
	<p><strong>How to Edit or Modify Data:</strong></p>
	<p>Data that user provide to Voice Caddie through the Site can be modified from user’s admin page or Voice Caddie account preferences. If users remove data from user’s Voice Caddie account, it will no longer appear to user or others who use the Voice Caddie Service. Backups of that data will remain associated with user’s Voice Caddie account and in our archive servers.</p>
	<p><strong>How To Deactivate User’s Voice Caddie Account:</strong></p>
	<p>User can deactivate user’s Voice Caddie account by contacting Customer Support. When users do, data that can identify user will be removed from the Voice Caddie Service, including but not limited to user’s email, name, photo(s), friends list and links to sites such as Facebook and Twitter. Backup copies of this data will be removed from our server based upon an automated schedule, which means it may persist in our archive for a short period. Voice Caddie may continue to use user’s de-identified data after user deactivate user’s account.</p>
	<p><strong>Voice Caddie’s Policies for Children:</strong></p>
	<p>Voice Caddie is not allowed at persons under the age of 13. We do not knowingly collect any PII from children under 13. If users are aware of a user under the age of 13 using Voice Caddie, please contact us at help@voicecaddie.com.</p>
	<p><strong>Can I Opt-out Of Receiving Voice Caddie Emails?</strong></p>
	<p>Of course! User can opt-out of receiving weekly summaries, achievement notifications, contests, giveaways, surveys, and promotional emails by changing the notification preferences in user’s account settings or by unsubscribing via the “Unsubscribe” link in any Voice Caddie email. Opting-out of these emails will not end transmission of important service-related emails that are necessary to user’s use of the Voice Caddie Service.</p>
	<p><strong>How Does Voice Caddie Keep My Data Safe?</strong></p>
	<p>Voice Caddie uses a combination of technical and administrative security controls to maintain the security of user’s data. If users have a security-related concern, please contact Customer Support.</p>
	<p><strong>How Does Voice Caddie Handle Data from International Visitors?</strong></p>
	<p>The Voice Caddie Service is operated entirely in the ROK (Republic of Korea) and is subject to ROK law. Any personal information that user provide to Voice Caddie is being transferred to Voice Caddie for use solely in the ROK and will be hosted on servers managed by ROK. Users consent to the transfer of user’s personal information to the ROK. If users are accessing the Voice Caddie Service from outside the ROK, please be advised that ROK law may not offer the same privacy protections as the law of user’s jurisdiction.</p>
	<p><strong>COOKIE POLICY</strong></p>
	<p>Voice Caddie use cookies and other technologies and web analytics to improve the functionality of the Voice Caddie Service.</p>
	<p><strong>Technologies We Use:</strong></p>
	<p>Cookies are text files that are sent by servers to web browsers and stored on user’s computer. Cookies tell us which parts of the Voice Caddie Service user have visited so we can figure out/estimate which promotions user may like to see or to alert user to software compatibility issues.<br>
	Social media tools, like widgets and plug-ins, are used. Therefore, users can share information from Voice Caddie on other sites such Facebook and Twitter. These interactive mini programs collect user’s IP address, record the pages user visit on our Sites, and set cookies that will enable the widget to function properly. User’s interactions with these widgets are governed by the privacy policy of the company providing them, not by Voice Caddie’s Privacy Policy. If we also use the Facebook and Twitter pixel tags, they could help us understand how effective our marketing is on those sites.</p>
	<h4><strong>Your Rights</strong></h4>
	<p>If you reside in the EEA, U.K., or Switzerland, you have the right, subject to the conditions set out in the General Data Protection Regulation (“GDPR”) or other applicable law, to request from Voice Caddie access to and rectification or erasure of your personal data, data portability, restriction of processing of your personal data, the right to object to processing of your personal data, and the right to lodge a complaint with a supervisory authority. For more information about these rights, please visit the&nbsp;<a href="https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens/my-rights_en/"><em><strong>European Commission’s “My Rights” page</strong></em></a>&nbsp;relating to GDPR, which can be displayed in a number of languages. If you reside outside of the EEA, U.K., and Switzerland, you may have similar rights under your local laws.</p>
	<p>To request access to or rectification, portability, or erasure of your personal data, or to delete your account, contact Voice Caddie by email at&nbsp;<a href="mailto:contact@voicecaddie.com">contact@voicecaddie.com</a>. Once request is received and processed, user’s account and personally identifiable information will be deleted.</p>
	<p>If you do not reside in the EEA, U.K., or Switzerland, but you believe you have a right to exercise these or any other rights under your local laws, contact Voice Caddie by email at&nbsp;<a href="mailto:contact@voicecaddie.com">contact@voicecaddie.com</a></p>
	<h4><strong><em>NOTICE FOR CALIFORNIA RESIDENTS OF PRIVACY PRACTICES AND RIGHTS</em></strong></h4>
	<p>If you are a California resident, California law may provide you with additional rights regarding your personal data. To learn more about your California privacy rights, visit the&nbsp;<em><strong><a href="http://www.oag.ca.gov/privacy/ccpa">CCPA Privacy Page.</a></strong></em></p>
	<p><em>All trademarks are the property of their respective owners.</em></p></div>
</div>